### ISSUE TITLE
Commands execute, feedback delayed, logs full of `Error executing action: Call timed out`

### ISSUE THREAD

**Issue by rohankapoorcom** [bitfocus/companion-module-homeassistant-server#36]
I've been using companion (various versions) with Home Assistant for ~4 years now (also various versions). In the past few weeks, I've noticed connection issues with Home Assistant and Companion that are disrupting this functionality.

Usually, making a change in an entity in Home Assistant is reflected (via the Feedback) in Companion instantly. This is no longer happening. Usually, pushing a companion button triggers an instant entity change in Home Assistant (or script call) and then the feedback updates instantly as well. However, this is also not happening. The entity change in Home Assistant does happen instantly, but the feedback update is often delayed by 20-40 seconds (if it even happens at all). This makes it very difficult to use for something like a microphone mute button since you don't know whether you are muted or not.

I've tested this with every version of Home Assistant from 2023.8 onwards until 2023.12 (I've not upgraded beyond that yet) along with every combination of Companion versions 3.1.2, 3.2.0, 3.2.1 and all of them exhibit the same behavior. The problem began while I was running Home Assistant 2023.8 and companion 3.1.2 (which had previously been working fine for months). During that time, I had added more automations and entities to Home Assistant.

I've also tried factory resetting Companion and then importing my configuration and the problem persists.

Log file attached: [3c64966b835b_companion_log_20240210-1249.csv](https://github.com/bitfocus/companion-module-homeassistant-server/files/14230505/3c64966b835b_companion_log_20240210-1249.csv)

Hopefully this is enough to figure out the issue or come up with more troubleshooting steps.

### Environment

```markdown
- OS: Ubuntu 22.04 (Docker Host), Windows 10 / Mac OS X Sonoma (both clients)
- Browser: Chrome 120.0.6099.201
- Companion Version: 3.2.1 (3.2.1+6676-stable-fa981d25)
- Home Assistant Version: 2023.12.4
```

**Comment by drewancil** [comment]
Not sure how helpful this is, but I also had trouble start about this time.  I have a large Home Assistant install, and just connecting Companion to HA will cause the companion device to lock up in 15-20 minutes.  I used Companion successfully before this.  I thought that maybe the device was overloaded (Raspberry Pi 4b/8GB), so I used an Intel NUC with 16GB of memory and an SSD and it locked that up too.  

Ive switched up Companion to use MQTT to interface with HA which is much less convenience and powerful, but it works.  Is this integration still maintained?

**Comment by drewancil** [comment]
I'm at 6510 entities today.  Yea, I wondered the same as you about size and this issue.  I figured if it was universal there would be more reports of issues.

The strange thing is that with a clean install, just enabling the HA integration in Companion causes the lockup - I don't even have to call any of the functions, use feedback, anything.  I was surprised it would use resources in this way.  I'm pretty handy with Python, but know zero about JS/TS, so I haven't even looked at the code.  

For MQTT, I just use the generic MQTT integration in Companion to send an MQTT message to a topic with an associated payload on the same MQTT broker I use for Home Assistant (I'm using the add-on).  Then I just create automations that trigger on various MQTT topics and run actions based on the payloads.  Not nearly as easy/seamless as Companion, and you don't get feedback, but for most of what I was doing with Companion, it ended up being pretty easy and I didn't need the feedback.  But, it was fast and everything was very stable under this method.  I'd much like to return to using the HA integration as it worked great for me before the timeframe you mentioned you started having trouble.  

I'm here to troubleshoot or test anything, but unfortunately I'm not able to provide the time or expertise to fix at code level.

**Comment by rohankapoorcom** [comment]
I tried updating to 3.2.2 (3.2.2+6688-stable-7417d2a0) today to see if it would make a difference. It behaves exactly the same as before.

> The strange thing is that with a clean install, just enabling the HA integration in Companion causes the lockup

Did you try a clean install of HA or of Companion only? I tried spinning up a minimal home assistant instance with no integrations configured and Companion did not lock up at all. So I believe there is a strong correlation with entity count and the instability that we are both seeing.

Thanks for sharing those details with your MQTT setup. Unfortunately for me I have about 30 entities / scripts that I control in Home Assistant through Companion and need the Feedback. I'm considering trying this [alternative software](https://github.com/basnijholt/home-assistant-streamdeck-yaml) instead, but I'm hopeful that this module in Companion can be fixed since I do use other functionality inside Companion directly.

**Comment by drewancil** [comment]
Yea, I periodically load the latest beta of Companion and test - locks up in 15-20 minutes or so.  

The clean instance I set up was Companion to my existing HA.  I did not try a clean HA, but I suspect my findings would equal yours.  

Did you watch attributes like memory, cpu, and disk i/o when you enable?  Does it exhaust any of those resources? 

It would be lovely to hear from the author - even if they do not plan to look into so we can make other arrangements if so.  It would be a shame because Companion works very well otherwise.

**Comment by rohankapoorcom** [comment]
> Did you watch attributes like memory, cpu, and disk i/o when you enable? Does it exhaust any of those resources?

On Companion? No, nothing appears to be exhausted. Nor on Home Assistant either since all of the clients are able to continue using it with no disruptions.

I had a crazy idea of setting up a second Home Assistant instance for just Companion use and having it handle a small subset of entities from the primary one, but that doesn't seem like a great idea from the maintainability perspective.

**Comment by rohankapoorcom** [comment]
@drewancil I haven't tested this yet, but found this [integration](https://github.com/koying/mqtt_discoverystream_ha) for Home Assistant that may be helpful. It looks like it will let you publish a copy of an entity over MQTT and have it automatically configured for discovery and interaction with a second Home Assistant instance. It seems like it would be a reasonable way to take the ~30 or so integrations that I care about interacting with via companion and put them on a dedicated Home Assistant instance for Companion and see if that stabilizes the problem.

It's not an ideal solution, but it seems like it could be the best workaround for me. I'll report back once I have some time to test it out (hopefully this weekend).

**Comment by rohankapoorcom** [comment]
I just finished setting up the integration mentioned in my previous message to publish specific entities (~45) to a new Home Assistant integration via MQTT. Pointing Companion to that instance of Home Assistant (with only those entities on it) resulted in a perfectly responsive and functional Companion setup.

I think this confirms that something is going awry with Companion when connected to Home Assistant instances with thousands of entities.

**Comment by prankousky** [comment]
Is there any initiative to fix this problem?  I just set up companion on a raspberry pi **just** to control Home Assistant. While it works fine, connection will drop quite soon, likely due to the mentioned huge amount of entities.

While the mqttstream and second HA is a nice idea, it'd be even better if it would still work out of the box for those of us with *too many* ;) entities.

**Comment by veilofsecurity** [comment]
I have started running into this recently as well. What I think is happening is Home Assistantant has started exposing significantly more entities than in the past. For example, Z-wave and Zigbee devices can expose dozens of entities each for things like updates, health, and configuration options. This has caused the number of entities to explode.

In the Bitfocus integration, it appears to load and constantly refresh every single entities (every 5s) as a variable and once you hit a certain number of entities it just breaks. I went through and disabled a bunch of entities I was not using and it did help a little but not nearly enough.

I also cloned the repo and enabled dev mode on Companion. I updated [this ](https://github.com/bitfocus/companion-module-homeassistant-server/blob/8c183b31715e59bea3d3307aecf80f663a6f2f95/src/index.ts#L21) to 15000 which seems to slow the refresh down to 15s. This has made it so that my integration at least stays running most of the time and actions typically work quickly but feedback is very slow and I do still get occasionally crashes where I have to disabled and re-enable the connection.

I tried to go through the code to see how to optimize this but I just don't know enough Typescript to do it. I think modifying the feedback code to only get updates for the entities in use would completely solve this issue. Or an alternate would be a configuration menu where we can choose which entities to expose to Companion.

Maybe @Julusian could take a look at the feasibility of toning down the entity subscription\polling?

**Comment by metril** [comment]
Same issue here. I've never programmed in Typescript before. However, from what knowledge I do have, I think I have an idea of what's going on. The plugin is using a websocket connect to Home Assistant. However, no filtering is done on the entities grabbed from Home Assistant. It also looks like the plugin then subscribes to every entity and keeps checking the state of every entity regardless of whether the entity is tied to a button or not.

**Comment by jonasrickert** [comment]
I ran into the same issue. My workaround was to move the companion instance off of the raspberry pi and move it to the same server where my homeassistant is running(runs on an i7-8700k). Then i simply connected the streamdeck on the raspberry pi via companion satellite. I saw a slight increase in cpu usage on the server while having ~1500 entities, but so far it is working great.

**Comment by veilofsecurity** [comment]
I have 4300+ enabled entities after extensive cleanup (down from 6500+) and am running HA in a VM with 8 Xeon cores, 16gb RAM, nVME SSD, and 10g NIC. Bitfocus is running on Mac Studio M1 Ultra with 10g NIC. Pretty sure the bottleneck is not resource related. It's just volume since we are constantly refreshing all entities. I'd imagine we could probably gain some minor efficiencies by moving HA to MySQL instead of SQLLite and maybe do some other low level tuning but its really not going to solve the underlying issue. 

For now I set up a second VM HA instance as suggested above but using HA-Remote and only exposing what I use for Bitfocus. Its back to working normal but has the overhead of managing a whole separate instance and making sure the used entities are exposed to that instance.

**Comment by sdholden28** [comment]
I've run into this as well on a fresh installation and a brand new Stream Deck+. I started with companion running on a pi4 with 8gb of ram and ran into this issue immediately. In my case, this particular stream deck is on my office desk, so I installed companion on my windows PC, which is always on and logged in anyway. No issues with that scenario. I can still add additional units via companion satellites, and there's no real downside to running it on my PC, but I'd still like to have it running on its own hardware, for reasons.

**Comment by Julusian** [comment]
I've pushed an update to the module which reduced the cpu impact on my dev machine from 0.5% to 0.1%, and my home setup from 16% to 2.5%

Hopefully it gives similar results for you

**Comment by drewancil** [comment]
I was out of town and unable to test right away, but I had some time last night - so far, so good!  I also upgraded to a Raspberry Pi 5 8GB, but it's been running 24+ hours now and only using 2GB total memory.  I'd like to run this a while longer to be sure, but I'm pretty sure this is resolved.  Thank you!!  Will be a huge improvement for me over the MQTT I had reverted to using.

**Comment by drewancil** [comment]
Ive been running this, and it works so much better in the usability department, but there is still an issue in designing the buttons that makes usability difficult.  When selecting a home assistant variable for use in feedback or a trigger, clicking the dropdown freezes the browser for around 30 seconds before the "Page is Unresponsive" dialog box is encountered.  Most of the time, it will not populate, but occasionally if I click the "Wait" option it will then respond when I can attempt to select the variable needed.  Other times, it will just lock the browser completely.  Seems very close - any ideas?

**Comment by rohankapoorcom** [comment]
Thanks @Julusian - I can confirm that this fixes my performance issues that were called out in the original message. I no longer need to the workaround of a second Home Assistant instance to ensure performance.
